# Training files
data:
    corpus_1:
        path_src: estr.filtered.lad.subword
        path_tgt: estr.filtered.tur.subword
        transforms: [filtertoolong]
    valid:
        path_src: extendedmix.tur-lad.filtered.test.lad.subword
        path_tgt: extendedmix.tur-lad.filtered.test.tur.subword
        transforms: [filtertoolong]

# For shared vocab, use only src_vocab, and no tgt_vocab
src_vocab: sp.onmt_vocab

share_vocab: 'true' 

src_vocab_size: 50000
tgt_vocab_size: 50000


# Tokenization options
# For shared subword model, use only src_subword_model, and no tgt_subword_model
src_subword_model: sp.model


early_stopping: 5
log_file: train_lad-tur_20052022.log

save_model: ./models/model_lad-tur

keep_checkpoint: 15
seed: 3435
train_steps: 2000000
valid_steps: 5000
save_checkpoint_steps: 5000
warmup_steps: 4000
report_every: 100

decoder_type: transformer
encoder_type: transformer
word_vec_size: 512
rnn_size: 512
layers: 6
transformer_ff: 2048
heads: 8

accum_count: 4
optim: adam
adam_beta1: 0.9
adam_beta2: 0.998
decay_method: noam
learning_rate: 2.0
max_grad_norm: 0.0
max_relative_positions: 16

batch_size: 1024
batch_type: tokens
normalization: tokens
dropout: 0.1  # or 0.3
label_smoothing: 0.1
valid_batch_size: 512

max_generator_batches: 2

param_init: 0.0
param_init_glorot: 'true'

world_size: 2
gpu_ranks: [0,1]

